### ISSUE TITLE
Restore on specific element/s

### ISSUE THREAD

**Issue by xviktorx** [AudithSoftworks/Uniform#316]
Hi,

I've found this:

You write, that: $.uniform.restore() does not need to be global; you now can use $('#myId').uniform.restore() instead to just restore some elements. Same thing for updates.

But it doesn't work for me... Here is example with commented wrong, and uncommented right use of restore. 

http://jsfiddle.net/Wp9kx/

Is that bug or feature? I can't use it by that commented way. 

Thanks, have a nice day.

**Comment by shehi** [comment]
https://jsfiddle.net/Shehi/ojbhvbk8/

Correct version should be: `$.uniform.restore(element)`. I will update docs accordingly.
