### ISSUE TITLE
Select auto width in Safari

### ISSUE THREAD

**Issue by eugeniojauregui** [AudithSoftworks/Uniform#326]
Hi!
I detected some problem in the visualisation of select fields in Safari, the width added by de plugin is smaller than the other browsers.
Some captures of the issue:

http://uniformjs.com/ ->
Google Chrome:
![image](https://f.cloud.github.com/assets/1844455/432732/3dbf2944-aead-11e2-8f3e-af2571dd0ee3.png)
Safari:
![image](https://f.cloud.github.com/assets/1844455/432735/4fc86ab0-aead-11e2-991c-7a5e50ffbea9.png)

Any idea why happens this and how to fixed?
Thanks!

**Comment by fidian** [comment]
Sounds like the same issue as #359
