### ISSUE TITLE
Submitting forms (via submit buttons or just hitting enter in forms) does that twice

### ISSUE THREAD

**Issue by Cage31** [AudithSoftworks/Uniform#328]
hello,
nice pluggin and good job.
I find a problem with it.
When we apply uniform on submit element (input or button with  type submit) the form submited twice.
Try this simple code with firebug. Just change links for css and js files. (sorry don't know how to put code)

![capture decran 2013-04-30 a 15 23 30](https://f.cloud.github.com/assets/2852664/444059/30f0a87a-b199-11e2-8d93-42776c4650e8.png)

The console firebug display 'go' twice.

Have an idea ?

thanks

**Comment by shehi** [comment]
Confirmed: https://jsfiddle.net/Shehi/nkks5Ly9/

Will look into it soon.
