### ISSUE TITLE
IE display problem with buttons, dropdown selection, etc.

### ISSUE THREAD

**Issue by mccullah** [AudithSoftworks/Uniform#336]
Buttons and dropdown selector boxes are jagged on the left side of the button/selector, only in browser IE (version 9). See http://officepoolstop.com.

Fantastic jquery plugin, BTW! 

Fred Williams

**Comment by shehi** [comment]
https://saucelabs.com/beta/tests/8f56f65e020f4d44be4147b580734c5f/watch

Everything looks OK to me. Not sure what you meant by "jagged".
