### ISSUE TITLE
Update checkbox parent span with checkedClass when checkbox checked state changes

### ISSUE THREAD

**Issue by jxpx777** [AudithSoftworks/Uniform#349]
Hi, guys. I work on 1Password and we've received some reports from users of sites using Uniform like http://letterboxd.com. The users were saying that the checkbox state wasn't properly restored when the user fills the login from 1Password. I checked, and we are indeed setting the checkbox.checked attribute and it's updating, but it seems Uniform isn't recognizing that change so the parent `<span>` isn't updating with the `checkedClass`. Is there something we can do to inform Uniform that we're filling the checkbox value or could you add change listeners to the checkboxes to set the span wrapper checked class?

Thanks!

**Comment by shehi** [comment]
As I stated in #348, you should `update()` your form elements with `setTimeout()` set for at least a millisecond. There is a possible race-condition where Uniform needs native browser update mechanisms (such as resetting a form, or changing the value of a uniform-ed element) to finish. It happens quite fast, just sometimes Uniform can be faster. Generally, when it comes to `input` elements, it's faster than Uniform, but with `select`s, even file upload `input`s it can be "slower". Thus, something like this is recommended - let's say for potential reset button handling: 

```
$("input[type='reset']").click(function(e) {
    setTimeout(function () {
        $uniformed.uniform.update();
    }, 1);
});
```
