### ISSUE TITLE
Callback for click on radio button

### ISSUE THREAD

**Issue by rajeev-grep** [AudithSoftworks/Uniform#351]
Hi

I am getting truble to find callback for click event on radio button.
I have to show some div when one of radio button is checked.

Is there any callback where i can call my own function whenever radio button get checked or unchecked?

Any hint or solution is highly appreciated.

**Comment by shehi** [comment]
http://stackoverflow.com/questions/2518421/jquery-find-events-handlers-registered-with-an-object
