### ISSUE TITLE
Submit button not hidden

### ISSUE THREAD

**Issue by softlion** [AudithSoftworks/Uniform#358]
In uniformHandlers for Buttons, I needed to add $el.hide(); after bindUi($el, $div, options); because both the uniform button and the original input type=submit were displayed.

With 2.0 PRE it was working correctly, but it was a long time ago ...

**Comment by shehi** [comment]
Please provide JSFiddle of some kind (preferrably based on [our default one](https://jsfiddle.net/Shehi/qgLwy8Ln/)). Due to time constraints, it's hard to create your scenarios.
