### ISSUE TITLE
Select boxes not sizing correctly in Firefox on OSX

### ISSUE THREAD

**Issue by patgaunt** [AudithSoftworks/Uniform#359]
Select boxes seem to be shorter on Firefox on OSX than on other browsers. This has caused an issue where I have a row of floated elements resulting in inconsistent spacing in Firefox. The issue can be seen on the demo page - see screenshot. The width of the select box is 99px in Chrome but only 80px in Firefox. Firefox on Windows displays the select boxes correctly.

![uniform-bug](https://f.cloud.github.com/assets/5469377/1225539/1c401b20-276b-11e3-810e-c3e6b317b179.gif)

**Comment by fidian** [comment]
@shehi - Is it worth investigating adding this CSS fix to `themes/_base/css/uniform._base.css`?

**Comment by shehi** [comment]
@fidian : I actually tested this in Safari on OS X and couldn't reproduce the issues mentioned here.

https://saucelabs.com/beta/manual/test_proxy/33fc72d951ae400988c63e35023115fd

+1 for adding those lines to CSS though.
