### ISSUE TITLE
How to make radio/checkbox/selecbox form elements readonly

### ISSUE THREAD

**Issue by iamshailendra** [AudithSoftworks/Uniform#375]
I want to make radio/checkbox/selecbox form elements readonly because i want to show pre-selected value.

I tried

$("input[type='radio'], input[type='checkbox'], select").attr('readonly', true);
$.uniform.update();

but its not working

**Comment by shehi** [comment]
Am I missing something, because `readonly` attribute has no effect, both in Chrome and FF: https://jsfiddle.net/Shehi/7a0hfcLe/

**Comment by shehi** [comment]
And there is no `readonly` attribute listed in MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by shehi** [comment]
Additionally, if you want to make something behave in "readonly" fashion, just add this in CSS for that element: `pointer-events: none`. That's it. Closing this one.
