### ISSUE TITLE
CDNjs integration

### ISSUE THREAD

**Issue by 7wonders** [AudithSoftworks/Uniform#377]
Worth making a note on the readme?

http://cdnjs.com/libraries/Uniform.js

**Comment by shehi** [comment]
@dodopok , I noticed you have submitted jquery.uniform to npm - could you please pass the ownership of that submission to me at npm? My username is @shehriyari there. Thanks.

**Comment by shehi** [comment]
@fidian any idea which files we should include in CDNjs configs? Plz see the link @7wonders shared. I can't decide whether to include minified file in it or not, as I remember reading CDNjs doesn't want minified files included in auto-update scenarios.

**Comment by fidian** [comment]
One should publish minified CSS and JS and not publish the larger versions per the cdnjs documentation:  https://github.com/cdnjs/cdnjs#user-content-conventions

To make the CSS work, the images will need to be hosted there as well.  So, at a minimum I would suggest hosting the *.min.js, *.min.css files and *.png.

**Comment by shehi** [comment]
https://github.com/cdnjs/cdnjs/pull/7685
