### ISSUE TITLE
Inputs hidden with style rules are made visible when .uniform() runs

### ISSUE THREAD

**Issue by ucavus** [AudithSoftworks/Uniform#382]
Uniform should copy `display: none` and `visibility: hidden` to the generated parent if set on the input itself when initialising. It should probably also override those properties on the input to make it explicitly visible, because the generated parent will handle display from then on. Restore would need to copy the generated parent's (current) value(s) back to the input.

**Comment by shehi** [comment]
[Couldn't reproduce](https://jsfiddle.net/Shehi/gef7kb7k/), neither via external, or inline CSS (varying Specificities of rules).
