### ISSUE TITLE
Hover state isn't correct on Radio Buttons

### ISSUE THREAD

**Issue by leejays** [AudithSoftworks/Uniform#387]
I've just found this great solution edited the template and implemented it and it works fine, all except the radio buttons do not have a hover state. This isn't anything I have done, as it doesn't work on http://uniformjs.com either.

I am using Windows 7, and have tried in a few browsers (IE, firefox, chrome)

The active state works, and the hover state works on a selected radio button, but not on the normal radio button.

I have looked through all the issues and couldn't find any post where this has been brought up before?

Is this a known bug?

Many thanks,

Lee

**Comment by shehi** [comment]
Seems to me it works: https://jsfiddle.net/Shehi/qgLwy8Ln/

Couldn't reproduce the described issue.
