### ISSUE TITLE
Issue in Firefox When Using Hidden Inputs with Checkboxes

### ISSUE THREAD

**Issue by martincarlin87** [AudithSoftworks/Uniform#398]
I had markup in the following format for all my checkboxes:

    <div class="control-group">
        <label class="control-label">Some Label</label>
        <div class="controls">
            <label class="checkbox">
                <input type="hidden" name=""  value="0" />
                <input type="checkbox" name="" value="1" />
           </label>
       </div>
    </div> 

This worked fine in Chrome and Safari but in Firefox the click doesn't change the state of the checkbox, you need to remove the hidden input and place it outside the container element you are using to initialise Uniform.

This is especially bothersome if you are using the Rails Checkbox Helper method as instead of an easy cut/paste you will have to re-write your checkbox markup manually.

Although I managed to fix it, I thought I'd post it incase others have the same issue.

Not sure if it could be a simple fix by excluding hidden inputs from being targeted by uniform.

**Comment by shehi** [comment]
Works as intended and desired: https://jsfiddle.net/Shehi/1vxvsgby/
