### ISSUE TITLE
Problem with non-breaking space (&nbsp;)

### ISSUE THREAD

**Issue by lucvdbos** [AudithSoftworks/Uniform#401]
I use a checkbox with non-breaking spaces. In the lookup it goes well, but when selecting you see the HMTL in the selectbox. What can be the problem?
```
 <option value="{$node.sid|escape}" title="{$node.path}" {if $node.sid eq $selected}selected="selected"{/if} >
        {capture name="node_caption"}[[$node.caption:raw]]{/capture}
        {$smarty.capture.node_caption|indent:$node.level:" &nbsp; &nbsp;"}({$node.listing_number})
</option>
{if isset($tree_values.$node_sid)}
        {include file="field_types^search/category_tree_option.tpl" tree_values=$tree_values parent=$node.sid selected=$selected} 
{/if}
```
![problem](https://cloud.githubusercontent.com/assets/680434/3075830/14395c00-e397-11e3-91a3-92c1e59956e2.png)

**Comment by shehi** [comment]
Jsfiddle would help in this situation. Need to be able to reproduce the exact scenario. Any chance one could be provided?

**Comment by shehi** [comment]
Couldn't reproduce: https://jsfiddle.net/Shehi/ehnhamxh/
