### ISSUE TITLE
uniform.default.css enhancements for textarea elements + other suggestions

### ISSUE THREAD

**Issue by blackfriar** [AudithSoftworks/Uniform#408]
Textarea is transparent. Why ????
Solution:
textarea.uniform {
	background: #fff url("images/bg-input.png") repeat-x 0 0;
}
textarea.uniform.active {
	background: #fff url("images/bg-input-focus.png") repeat-x 0 0;
}

If you want to center a select tag the text will shift to right.
Solution:
div.selector span {
	text-align: left;
	text-overflow: ellipsis;
	display: block;
	overflow: hidden;
	white-space: nowrap;
	background-position: right 0;
	height: 26px;
	line-height: 26px;
	padding-right: 10px;
	cursor: pointer;
	width: 100%;
	display: block;
}

**Comment by shehi** [comment]
Can we have a PR @blackfriar ?
