### ISSUE TITLE
Performance absolute bad on "update"

### ISSUE THREAD

**Issue by pixel-shock** [AudithSoftworks/Uniform#415]
Hi,

did you take a look at the performance tools in your browser? If I call the "udpate" function my browser hangs about 40s while updating 71 form elements (yes, 71 - it's a search form with filters etc.)

**EDIT** The init function is much faster ... maybe the easiest update solution is to destroy the changes that where made by the init function an reinit this again instead of swapping styles and reapply them?

Cheers
Tino

**Comment by jenbhu** [comment]
i have 36 elements, and it hangs for about 1-2 seconds.
