### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by heaversm** [AudithSoftworks/uniform#416]
Looks like http://uniformjs.com/ is down.

**Comment by muffinjello** [comment]
+1

**Comment by Tudumanu** [comment]
http://web.archive.org/web/20150114093618/http://uniformjs.com/

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by shehi** [comment]
@pixelmatrix , I noticed you still have the domain owned, is the problem hosting related? If so, I could get it hosted, if you shared the original website's code.

**Comment by fidian** [comment]
GitHub can host the site as well as long as someone owns the domain and points to their servers.  https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by shehi** [comment]
Yea, I know that. So, @pixelmatrix , what's the situation re the domain? :)

**Comment by pixelmatrix** [comment]
honestly it's been so long since i've touched this project that I don't recall where it was hosted. Here's a link to the site's source if anyone wants to either add it to the repo or host it somewhere. I can also toss it in a public s3 bucket if that is helpful. https://www.dropbox.com/s/lt1eas4f1xtalj6/uniform-site.zip?dl=0

**Comment by shehi** [comment]
What about the domain?

**Comment by shehi** [comment]
Thanks to @pixelmatrix , we finally managed to move UniformJs to its new home at AudithSoftworks/uniform, where we will be maintaining it from now on.

The new website is located at http://opensource.audith.org/uniform (the old domain will be redirecting to this new location until Feb 2017) for the moment. I plan to move all the documentation to Github Wiki soon.
