### ISSUE TITLE
Uncaught ReferenceError: returnFalse is not defined

### ISSUE THREAD

**Issue by antonysuthakarj** [AudithSoftworks/Uniform#421]
I have a file upload control in one of my web page. When I try to initialize the file upload control with uniform.js 2.2.0 the latest version, it shows some script error in the browser console. So that it blocked all the script after the particular line.

Please find the sample code in [jsfiddle](http://jsfiddle.net/antonysuthakarj/bm552h4y/1/)

Help me to find out a solution for this!.

**Comment by shehi** [comment]
Closing this in favor of #422.

**Comment by shehi** [comment]
I will be releasing a patch version today. Not sure how long it will take for CDNjs to catch up, but you can get the latest version via NPM/Bower once I am done.

**Comment by shehi** [comment]
Ok, NPM/Bower release v2.2.1 is out.

**Comment by shehi** [comment]
https://cdnjs.com/libraries/Uniform.js

**Comment by antonysuthakarj** [comment]
Team,
Thank you all for your great support.

Great Work !!!

On Mon, May 9, 2016 at 5:59 PM, Şəhriyar İmanov <notifications@github.com>
wrote:

> https://cdnjs.com/libraries/Uniform.js
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AudithSoftworks/Uniform/issues/421#issuecomment-217851048>
>



-- 
With Thanks & Regards
ANTONY SUTHAKAR J.
