### ISSUE TITLE
Selected option won't be applied in Android / Chrome

### ISSUE THREAD

**Issue by bucha** [AudithSoftworks/Uniform#423]
Hello,

we're using Uniform for quite a while now and are pretty happy with it.

Recently we encountered a problem though, that seems to happen only on an up-to-date Android phone or its Chrome browser (Android 6.0.1 w/ Chrome 50.0.2661.89 here):
When the user taps on a select, the selected option won't be applied. Sometime there appears some kind of flickering with it, when Chrome is fading in the options-overlay.

We debugged it down to the `mousedown` event, which is bound within the `bindUi`method.
The following line seems to cause the problem:
```js
$target.addClass(options.activeClass);
```

My guess is, that by adding the class to the outer div, the browser has to repaint the area (which would also explain the flickering).
Thereafter it might not count the user's selection as valid anymore, as the circumstances changed.

After we deactivated the above line, the UI was responding as usual – except for the missing class obviously.

Best regards,
Alex

```js
function bindUi($el, $target, options) {
        bindMany($el, options, {
            focus: function () {
                $target.addClass(options.focusClass);
            },
            blur: function () {
                $target.removeClass(options.focusClass);
                $target.removeClass(options.activeClass);
            },
            mouseenter: function () {
                $target.addClass(options.hoverClass);
            },
            mouseleave: function () {
                $target.removeClass(options.hoverClass);
                $target.removeClass(options.activeClass);
            },
            "mousedown touchbegin": function () {
                if (!$el.is(":disabled")) {
                    $target.addClass(options.activeClass); // <-- this leads to the problem
                }
            },
            "mouseup touchend": function () {
                $target.removeClass(options.activeClass);
            }
        });
    }
```

**Comment by shehi** [comment]
The flickering might be related to #424 as both cases are related to v50 of Chrome. I can't test v50 as my Android is already on v51. Can you confirm this situation continues on in v51 as well? Also providing some JSFiddle simulating your scenario would help a lot.

**Comment by shehi** [comment]
This problem looks like a browser bug and affects only Chrome 50, and according to some additional reports, Chrome 51. It seems to be solved in Chrome 52. Please report here if you encounter the problem in more recent versions. Closing for now.
