### ISSUE TITLE
DevOps Overhaul

### ISSUE THREAD

**Issue by shehi** [AudithSoftworks/Uniform#426]
In v3.0, I plan to enhance package capabilities from DevOps standpoint:
- [x] Gulp support,
- [x] Increased NPM support,
- [x] ~~Compass support~~ (won't be directly implemented, but should work with current configuration if one chooses to do so),
- [x] Docker support,
- [x] Streamlining, by completely separating real sources (SCSS, Javascript sources) from generated assets (Minified CSS and Javascript files, readable CSS),
- [ ] Unit tests,
- [ ] SauceLabs integration.

No new features will be introduced in this release. @fidian 's old `v3` branch will be renamed and archived for future development of v4.0 release.

CC: @fidian , @pixelmatrix

**Comment by fidian** [comment]
You can completely erase the 3.0 branch as well if you are so inclined.  You've put more work into this project in the last month than I have for the past year!

**Comment by shehi** [comment]
Why would I lose an invaluable work, idea? Never mate. I haven't thoroughly checked your code yet, and can't risk losing an interesting approach that might exist in there. I just had to rename it, because I need ambiguous branch names for each version we release.

**Comment by fidian** [comment]
Understood.  I intended to convey the idea that I have no attachment to the branch.  Renaming/deleting it is ok by me.  I also wanted to show support for what you are doing and didn't want to be in your way.  :-)

Good luck with 3.0!
