### ISSUE TITLE
Website download link should point to 2.2.2, currently points to 2.2.0

### ISSUE THREAD

**Issue by pouellet** [AudithSoftworks/Uniform#431]
The uniform website (http://opensource.audith.org/uniform) download link points to the 2.2.0 tag, which has issue #421. It would be great to update to point to the 2.2.2 tag.

**Comment by shehi** [comment]
It's actually 3.0.0 - updated. I plan to revamp whole site, guess forgot to update the current old one when I released 3.*. Thanks for reporting.
