### ISSUE TITLE
508 Compliancy "aria-checked"

### ISSUE THREAD

**Issue by googabeast** [AudithSoftworks/Uniform#437]
I have a fix for you to comply with 508 requirements. For radio and checkbox the "aria-checked" attributes are required.

The changes are extremely minor and because your structure is well organized I have done the following. This has been tested in all major browsers and back to IE9+. Passed HTML validation and 508 Wc3 standards.

LINE 148 - Insert attr modifier.
`
    if (options.aria) {
        $el.attr("aria-checked", isChecked);
    }
`

LINE 910 - Insert default option for "aria"
`
    aria:true,
`

Happy Coding and thank you for a great structured utility plugin!

**Comment by googabeast** [comment]
Just thought of this last thing, I didn't code in a "if has attribute" but if you wanted a quick check then I'm sure this would work. 

`
        if(typeof $el.attr(att) !== typeof undefined && $el.attr(att) !== false){
            return true;
        }else{
            return false;
        };
`

**Comment by shehi** [comment]
Send in a Pull Request to 4.0 branch please.
