### ISSUE TITLE
Different label for file selection boxes that allow selection of multiple files

### ISSUE THREAD

**Issue by manish-in-java** [AudithSoftworks/Uniform#441]
HTML5 `<input type="file" />` controls support a `multiple` attribute that allows selection of multiple files using the same file selection control.
We use `<input type="file" multiple="multiple" />` extensively in our application that also uses the Uniform plugin. However, the text label shown for these fields still reads `Choose File` whereas `Choose Files` would be more appropriate.
Can an option `filesButtonHtml` be added that could be set to `Choose Files` by default and used if the file input control support multiple selections?

**Comment by manish-in-java** [comment]
Submitted pull request #442 for this.

**Comment by shehi** [comment]
This is already implemented.
