### ISSUE TITLE
Multiple file selected but only one filename shown

### ISSUE THREAD

**Issue by ducman** [AudithSoftworks/Uniform#445]
UI issue with `<input type="file" multiple />` ; occurred after selecting multiple files but only one filename is shown to the user causing them to be confused.

The easy fix is to change `setFilename` to detect `multiple` and use `$el.files` to get a comma delimited list of filenames.

**Comment by shehi** [comment]
Please kindly provide JSFiddle example (we have starting example in the readme).

**Comment by ducman** [comment]
Here is a codepen of it [here](https://codepen.io/ducman/pen/mwaYLx).

Note: the temp fix is just for me to get around the issue right now.
