### ISSUE TITLE
getComputedStyle undefined

### ISSUE THREAD

**Issue by ldoloscan** [AudithSoftworks/Uniform#446]
Hey guys,

I have an error using this plugin with Angular 4,
it says `ERROR TypeError: Cannot read property 'getComputedStyle' of undefined`,

how could i get rid of this error, it's blocking the whole page and don't even initialize checkbox styling.

Thanks in advance.

**Comment by ldoloscan** [comment]
I fixed it by injecting `jquery.uniform.standalone.js` right into index.html file, but I don't understand why this won't work by importing it in component, any ideas ?

**Comment by tvarwig** [comment]
Having same issue any update?

**Comment by ldoloscan** [comment]
@tvarwig Have you tried to put this into index.html file by `<script/>` tag ?

**Comment by tvarwig** [comment]
@ldoloscan I did place it in my index.html file as a separate script. 'jQuery' and the library 'uniform' are loading and defined. I did console.log my element to make sure it is finding it. This morning just for testing I tried in vuejs and am getting the same error as with angular 4. Other jQuery libs like select2 are loading and rendering just fine.

**Comment by ldoloscan** [comment]
@tvarwig Try to put js file in in cli.json, in script key, and what I did after was in ngOnInit:
```
        $(this._rootNode.nativeElement).find('input').uniform({
            wrapperClass: this.classes
        });
```
and also the checkbox styles imported in component `import 'jquery.uniform/dist/css/default.css';`

Try this way, hope it'll help !!!

**Comment by tvarwig** [comment]
I did get it working. I noticed If I place the import uniform script in the component it will not load on first render/mount. If I go to a different route and back to the page uniform loads fine for VueJS anyway. Havn't tested it with Angular yet. I don't believe this is a vuejs or angular issue because other libs load without this workaround

**Comment by shehi** [comment]
Is this resolved?
