### ISSUE TITLE
select boxes are not displayed properly when using tabbed panels

### ISSUE THREAD

**Issue by vesper8** [AudithSoftworks/Uniform#448]
I have multiple tabs which each hold a form. I noticed that Uniform only styles the tab correctly in the tab that is visible onload, the forms inside the other tabs have also had Uniform applied to them as evidenced by the 'agent' styling.. however the select boxes are only 25px

Is there a call that can be made to redraw the table? Or a technique for addressing forms that don't look right and weren't visible when Uniform was applied?

Thanks..

**Comment by shehi** [comment]
Why don't you use something like ```$.uniform.update([elem/selector string]);``` ? Check Wiki for more info.

**Comment by vesper8** [comment]
Thanks! I'll keep that in mind. I got around the problem by setting a fixed width

One weight thing though is that setting a fixed width on select inputs by itself didn't fix the problem, only once I added the !important did it work
