### ISSUE TITLE
Get value from radio checked

### ISSUE THREAD

**Issue by netopvh** [AudithSoftworks/Uniform#451]
Hello, I'm trying to get the value checked from a radio field, but jquery always returns undefined, how can I get the value of the selected item?

**Comment by big-sponge** [comment]
Me Too

**Comment by big-sponge** [comment]
I don't know how to get the value checked from a radio field.

**Comment by webinvader** [comment]
You should try to use $(this).find(":checked").val() on the "change" event handler

**Comment by shehi** [comment]
Is this resolved?
